/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d756dcffeed02ec1e27e624f5851793a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "CounterAgent" | "ChatAgent";
	}
	interface Env {
		AI: Ai;
		CounterAgent: DurableObjectNamespace<import("./src/server").CounterAgent>;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
